/**
 * Canonical Effect v4 graph-template catalog.
 *
 * This is the single authoritative array of Effect v4 graph templates. It is
 * generated from the leaf packs directly — the modules that define templates —
 * and does NOT chain through the historical `expanded-with-X` catalogs, so it
 * has no accidental dependency on that chaining.
 *
 * Every canonical template appears exactly once. Each distinct pack array is
 * imported exactly once, from the module that declares it; packs that merely
 * re-export another pack's array are not imported for that name. Composite
 * arrays whose templates are all reachable through their constituent packs
 * are omitted entirely (effectV4GuideGraphTemplateInputs, effectPlatformGraphTemplateInputs).
 *
 * Generated by `core-templates/.probe/build-canonical-catalog.mts`.
 */

import type { AnyEffectFamilyTemplateDefinitionInput } from './effect-template-helpers.js'

import { basePatternGraphTemplateInputs } from './e-samplesBasePatterns.js'
import { coreGraphTemplateInputs } from './e-samplesBasePatterns.js'
import { effectApplicationGraphTemplateInputs } from './effect-application-templates.js'
import { effectBatchingGraphTemplateInputs } from './effect-batching-templates.js'
import { effectBehaviourGraphTemplateInputs } from './effect-behaviour-templates.js'
import { effectBigDecimalGraphTemplateInputs } from './effect-bigdecimal-templates.js'
import { effectCacheGraphTemplateInputs } from './effect-cache-templates.js'
import { effectCauseGraphTemplateInputs } from './effect-cause-templates.js'
import { effectChunkGraphTemplateInputs } from './effect-chunk-templates.js'
import { effectConcurrencyGraphTemplateInputs } from './effect-concurrency-templates.js'
import { effectConfigV4GraphTemplateInputs } from './effect-config-templates.js'
import { effectCoordinationGraphTemplateInputs } from './effect-coordination-templates.js'
import { effectDataGraphTemplateInputs } from './effect-data-templates.js'
import { effectDateTimeGraphTemplateInputs } from './effect-datetime-templates.js'
import { effectDurationGraphTemplateInputs } from './effect-duration-templates.js'
import { effectErrorGraphTemplateInputs } from './effect-error-management-v4-templates.js'
import { effectEsToolkitGraphTemplateInputs } from './effect-es-toolkit-templates.js'
import { effectExitGraphTemplateInputs } from './effect-exit-templates.js'
import { effectFileSystemGraphTemplateInputs } from './effect-file-system-templates.js'
import { effectHashSetGraphTemplateInputs } from './effect-hash-set-templates.js'
import { effectObservabilityGraphTemplateInputs } from './effect-observability-v4-templates.js'
import { effectOptionGraphTemplateInputs } from './effect-option-templates.js'
import { effectPathGraphTemplateInputs } from './effect-path-templates.js'
import { effectPlatformLoggerGraphTemplateInputs } from './effect-platform-logger-templates.js'
import { effectRedactedGraphTemplateInputs } from './effect-redacted-templates.js'
import { effectResourceGraphTemplateInputs } from './effect-resource-templates.js'
import { effectResultGraphTemplateInputs } from './effect-result-templates.js'
import { effectScheduleGraphTemplateInputs } from './effect-schedule-templates.js'
import { effectSchemaGraphTemplateInputs } from './effect-schema-templates.js'
import { effectServiceLayerGraphTemplateInputs } from './effect-service-layer-templates.js'
import { effectSinkV4GraphTemplateInputs } from './effect-sink-v4-templates.js'
import { effectStreamSinkRealWorldGraphTemplateInputs } from './effect-stream-sink-real-world-templates.js'
import { effectStreamV4GraphTemplateInputs } from './effect-stream-v4-templates.js'
import { effectTerminalGraphTemplateInputs } from './effect-terminal-templates.js'
import { effectGraphTemplateInputs } from './effect-ts.js'
import { effectV4AiFoundationalGraphTemplateInputs } from './effect-v4-ai-foundational-templates.js'
import { effectV4ApplicationAssemblyFoundationalGraphTemplateInputs } from './effect-v4-application-assembly-foundational-templates.js'
import { effectV4ApplicationAssemblyCompositionGraphTemplateInputs } from './effect-v4-application-assembly-templates.js'
import { effectV4BehavioralTestingGraphTemplateInputs } from './effect-v4-behavioral-testing-templates.js'
import { effectV4ChildProcessFoundationalTemplateInputs } from './effect-v4-child-process-foundational-templates.js'
import { effectV4ChildProcessOsIntegrationCompositionTemplateInputs } from './effect-v4-child-process-os-integration-templates.js'
import { effectV4CliCommandApplicationGraphTemplateInputs } from './effect-v4-cli-command-application-templates.js'
import { effectV4CliFoundationalGraphTemplateInputs } from './effect-v4-cli-foundational-templates.js'
import { effectV4ClusterDistributedServiceGraphTemplateInputs } from './effect-v4-cluster-distributed-service-templates.js'
import { effectV4ClusterFoundationalGraphTemplateInputs } from './effect-v4-cluster-foundational-templates.js'
import { effectV4DurableWorkflowCompositionGraphTemplateInputs } from './effect-v4-durable-background-workflow-templates.js'
import { effectV4DurableWorkflowFoundationalGraphTemplateInputs } from './effect-v4-durable-workflow-foundational-templates.js'
import { effectV4EventLogOfflineFirstCompositionGraphTemplateInputs } from './effect-v4-eventlog-offline-first-templates.js'
import { effectV4EventLogPersistenceFoundationalGraphTemplateInputs } from './effect-v4-eventlog-persistence-foundational-templates.js'
import { effectV4FaultInjectionGraphTemplateInputs } from './effect-v4-fault-injection-templates.js'
import { effectV4HttpApiFoundationalGraphTemplateInputs } from './effect-v4-http-api-foundational-templates.js'
import { effectV4HttpFoundationalGraphTemplateInputs } from './effect-v4-http-foundational-templates.js'
import { effectV4HttpRestServiceBoundaryGraphTemplateInputs } from './effect-v4-http-rest-service-boundary-templates.js'
import { effectV4OpenApiGeneratedIntegrationGraphTemplateInputs } from './effect-v4-openapi-generated-integration-templates.js'
import { effectV4OpenApiGeneratorFoundationalGraphTemplateInputs } from './effect-v4-openapi-generator-foundational-templates.js'
import { effectV4OperationsFoundationalGraphTemplateInputs } from './effect-v4-operations-foundational-templates.js'
import { effectV4OtlpObservabilityFoundationalGraphTemplateInputs } from './effect-v4-otlp-observability-foundational-templates.js'
import { effectV4ProductionObservabilityGraphTemplateInputs } from './effect-v4-production-observability-templates.js'
import { effectV4RequirementsGraphTemplateInputs } from './effect-v4-requirements-templates.js'
import { effectV4ResilienceFoundationalGraphTemplateInputs } from './effect-v4-resilience-foundational-templates.js'
import { effectV4ResilienceWorkerGraphTemplateInputs } from './effect-v4-resilience-worker-templates.js'
import { effectV4ResourceGraphTemplateInputs } from './effect-v4-resource-templates.js'
import { effectV4RpcFoundationalGraphTemplateInputs } from './effect-v4-rpc-foundational-templates.js'
import { effectV4RpcServiceBoundaryGraphTemplateInputs } from './effect-v4-rpc-service-boundary-templates.js'
import { effectV4RuntimeGraphTemplateInputs } from './effect-v4-runtime-templates.js'
import { effectV4SecurityCrossBoundaryTemplateInputs } from './effect-v4-security-cross-boundary-templates.js'
import { effectV4SecurityFoundationalTemplateInputs } from './effect-v4-security-foundational-templates.js'
import { effectV4SocketFoundationalGraphTemplateInputs } from './effect-v4-socket-foundational-templates.js'
import { effectV4SocketStreamingBoundaryGraphTemplateInputs } from './effect-v4-socket-streaming-boundary-templates.js'
import { effectV4SqlFoundationalGraphTemplateInputs } from './effect-v4-sql-foundational-templates.js'
import { effectV4SqlRepositoryTransactionGraphTemplateInputs } from './effect-v4-sql-repository-transaction-templates.js'
import { effectV4TestingFoundationalGraphTemplateInputs } from './effect-v4-testing-foundational-templates.js'
import { effectV4TransactionFoundationalTemplateInputs } from './effect-v4-transaction-foundational-templates.js'
import { effectV4TransactionalCoordinationTemplateInputs } from './effect-v4-transactional-coordination-templates.js'
import { effectWorkflowGraphTemplateInputs } from './effect-workflow-templates.js'
import { esToolkitGraphTemplateInputs } from './es-toolkit-templates.js'

/**
 * Every canonical Effect v4 graph template, exactly once.
 *
 * 1794 distinct modelIds across 76 pack arrays.
 * 3 in-catalog re-exports were dropped by the modelId dedupe;
 * every one is a single-digest benign re-export of a template that survives
 * in an earlier pack.
 *
 * `concat` is used instead of a spread literal so the compiler checks each
 * pack against the annotated element type; a single 75-way spread literal
 * would infer a union of every pack's literal template type, which is too
 * complex to represent (TS2590).
 */
const allEffectV4Templates: AnyEffectFamilyTemplateDefinitionInput[] = (
	[] as AnyEffectFamilyTemplateDefinitionInput[]
).concat(
	basePatternGraphTemplateInputs,
	coreGraphTemplateInputs,
	effectApplicationGraphTemplateInputs,
	effectBatchingGraphTemplateInputs,
	effectBehaviourGraphTemplateInputs,
	effectBigDecimalGraphTemplateInputs,
	effectCacheGraphTemplateInputs,
	effectCauseGraphTemplateInputs,
	effectChunkGraphTemplateInputs,
	effectConcurrencyGraphTemplateInputs,
	effectConfigV4GraphTemplateInputs,
	effectCoordinationGraphTemplateInputs,
	effectDataGraphTemplateInputs,
	effectDateTimeGraphTemplateInputs,
	effectDurationGraphTemplateInputs,
	effectErrorGraphTemplateInputs,
	effectEsToolkitGraphTemplateInputs,
	effectExitGraphTemplateInputs,
	effectFileSystemGraphTemplateInputs,
	effectHashSetGraphTemplateInputs,
	effectObservabilityGraphTemplateInputs,
	effectOptionGraphTemplateInputs,
	effectPathGraphTemplateInputs,
	effectPlatformLoggerGraphTemplateInputs,
	effectRedactedGraphTemplateInputs,
	effectResourceGraphTemplateInputs,
	effectResultGraphTemplateInputs,
	effectScheduleGraphTemplateInputs,
	effectSchemaGraphTemplateInputs,
	effectServiceLayerGraphTemplateInputs,
	effectSinkV4GraphTemplateInputs,
	effectStreamSinkRealWorldGraphTemplateInputs,
	effectStreamV4GraphTemplateInputs,
	effectTerminalGraphTemplateInputs,
	effectGraphTemplateInputs,
	effectV4AiFoundationalGraphTemplateInputs,
	effectV4ApplicationAssemblyFoundationalGraphTemplateInputs,
	effectV4ApplicationAssemblyCompositionGraphTemplateInputs,
	effectV4BehavioralTestingGraphTemplateInputs,
	effectV4ChildProcessFoundationalTemplateInputs,
	effectV4ChildProcessOsIntegrationCompositionTemplateInputs,
	effectV4CliCommandApplicationGraphTemplateInputs,
	effectV4CliFoundationalGraphTemplateInputs,
	effectV4ClusterDistributedServiceGraphTemplateInputs,
	effectV4ClusterFoundationalGraphTemplateInputs,
	effectV4DurableWorkflowCompositionGraphTemplateInputs,
	effectV4DurableWorkflowFoundationalGraphTemplateInputs,
	effectV4EventLogOfflineFirstCompositionGraphTemplateInputs,
	effectV4EventLogPersistenceFoundationalGraphTemplateInputs,
	effectV4FaultInjectionGraphTemplateInputs,
	effectV4HttpApiFoundationalGraphTemplateInputs,
	effectV4HttpFoundationalGraphTemplateInputs,
	effectV4HttpRestServiceBoundaryGraphTemplateInputs,
	effectV4OpenApiGeneratedIntegrationGraphTemplateInputs,
	effectV4OpenApiGeneratorFoundationalGraphTemplateInputs,
	effectV4OperationsFoundationalGraphTemplateInputs,
	effectV4OtlpObservabilityFoundationalGraphTemplateInputs,
	effectV4ProductionObservabilityGraphTemplateInputs,
	effectV4RequirementsGraphTemplateInputs,
	effectV4ResilienceFoundationalGraphTemplateInputs,
	effectV4ResilienceWorkerGraphTemplateInputs,
	effectV4ResourceGraphTemplateInputs,
	effectV4RpcFoundationalGraphTemplateInputs,
	effectV4RpcServiceBoundaryGraphTemplateInputs,
	effectV4RuntimeGraphTemplateInputs,
	effectV4SecurityCrossBoundaryTemplateInputs,
	effectV4SecurityFoundationalTemplateInputs,
	effectV4SocketFoundationalGraphTemplateInputs,
	effectV4SocketStreamingBoundaryGraphTemplateInputs,
	effectV4SqlFoundationalGraphTemplateInputs,
	effectV4SqlRepositoryTransactionGraphTemplateInputs,
	effectV4TestingFoundationalGraphTemplateInputs,
	effectV4TransactionFoundationalTemplateInputs,
	effectV4TransactionalCoordinationTemplateInputs,
	effectWorkflowGraphTemplateInputs,
	esToolkitGraphTemplateInputs,
)

export const effectV4CanonicalGraphTemplateInputs = allEffectV4Templates.filter(
	(template, index, self) => self.findIndex((other) => other.modelId === template.modelId) === index
) satisfies readonly AnyEffectFamilyTemplateDefinitionInput[]

