import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import {
	compileArtifactSet,
	createArtifactSetWorkspaceSnapshotHash,
	createTemplateRegistryFromManifests,
	defineTemplate,
	fragmentCollectionPort,
	type ArtifactSetPlan,
	type SynthesisGraph
} from 'synthesize-regions'
import {
	validateEditStarterGraph,
	validateEditTemplateManifests
} from '../core-templates/test/fixtures/validate-edit-templates.js'
import { assertOk, block, code, collection, fact, literal, raw, step, writeOutput } from './shared.js'
import { coreRegistry, projectRoot } from './shared.js'

export const id = '04-artifact-set-pipeline'
export const title = 'Layer 4 - the artifact-set pipeline'

const fixtureRoot = join(projectRoot, 'core-templates/test/fixtures/abstract-reasoning-graph')

/** A source-file wrapper so any statement collection can become its own module. */
const demoModuleSourceFile = defineTemplate({
	modelId: 'DemoModuleSourceFile',
	version: '1.0.0',
	description: 'Wraps an ordered declaration collection in a complete module.',
	inputs: {
		declarations: fragmentCollectionPort({
			regionKind: 'statement',
			accepts: { outputKind: 'statement' },
			minItems: 1,
			separator: '\n\n',
			description: 'Top-level declarations, in source order.'
		})
	},
	output: { kind: 'sourceFile', description: 'Complete module source file.' },
	source: '/** @TYPE statement id=declarations **/export {};/** @END **/'
})

const demoGreetingDeclaration = defineTemplate({
	modelId: 'DemoGreetingDeclaration',
	version: '1.0.0',
	description: 'Declares the greeting function exported by the generated service module.',
	inputs: {},
	output: { kind: 'statement', description: 'Greeting function declaration.' },
	source: 'export const greet = (name: string): string => `Hello, ${name}!`'
})

const demoGreetingImport = defineTemplate({
	modelId: 'DemoGreetingImport',
	version: '1.0.0',
	description: 'Imports the greeting service generated by another artifact in this demo plan.',
	inputs: {},
	output: { kind: 'statement', description: 'Greeting service import declaration.' },
	source: 'import { greet } from "./services/greeting-service.js"'
})

const demoGreetingUse = defineTemplate({
	modelId: 'DemoGreetingUse',
	version: '1.0.0',
	description: 'Uses the greeting function imported from another generated artifact.',
	inputs: {},
	output: { kind: 'statement', description: 'Exported greeting result.' },
	source: 'export const message: string = greet("artifact set")'
})

function capturedWorkspace(): Record<string, string> {
	return {
		'tsconfig.json': readFileSync(join(fixtureRoot, 'tsconfig.json'), 'utf8'),
		'src/blackboard/reasoning-graph.ts': readFileSync(join(fixtureRoot, 'src/blackboard/reasoning-graph.ts'), 'utf8'),
		'src/domain/evidence.ts': readFileSync(join(fixtureRoot, 'src/domain/evidence.ts'), 'utf8')
	}
}

export function run(): void {
	step(
		title,
		'One plan, several graphs, several target files, and a captured workspace.\n' +
		'Each graph is compiled independently, the edits are assembled in authored\n' +
		'order, and the assembled result is statically validated before any of it is\n' +
		'called a change.'
	)

	const registry = createTemplateRegistryFromManifests(validateEditTemplateManifests)
	registry.registerAll([
		demoModuleSourceFile,
		demoGreetingDeclaration,
		demoGreetingImport,
		demoGreetingUse,
		...coreRegistry().list()
	])
	fact('registry', `${validateEditTemplateManifests.length} validate-edit manifests + ${coreRegistry().list().length} curated templates`)

	const greetingModule: SynthesisGraph = {
		nodes: [
			{
				id: 'greet',
				templateId: 'DemoGreetingDeclaration',
				inputs: {}
			}
		],
		finalNodeId: 'greet'
	}

	const mainModule: SynthesisGraph = {
		nodes: [
			{
				id: 'service-import',
				templateId: 'DemoGreetingImport',
				inputs: {}
			},
			{
				id: 'message',
				templateId: 'DemoGreetingUse',
				inputs: {}
			},
			{
				id: 'file',
				templateId: 'DemoModuleSourceFile',
				inputs: { declarations: collection('service-import', 'message') }
			}
		],
		finalNodeId: 'file',
		goal: { outputKind: 'sourceFile' }
	}

	const plan: ArtifactSetPlan = {
		artifacts: [
			{
				id: 'abstract-reasoning-graph',
				graph: validateEditStarterGraph,
				target: { kind: 'createFile', path: 'src/reasoning/abstract-reasoning-graph.ts' }
			},
			{
				id: 'greeting-service',
				graph: {
					nodes: [...greetingModule.nodes, {
						id: 'file',
						templateId: 'DemoModuleSourceFile',
						inputs: { declarations: collection('greet') }
					}],
					finalNodeId: 'file',
					goal: { outputKind: 'sourceFile' as const }
				},
				target: { kind: 'createFile', path: 'src/services/greeting-service.ts' }
			},
			{
				id: 'main',
				graph: mainModule,
				target: { kind: 'createFile', path: 'src/main.ts' }
			}
		]
	}

	const workspaceFiles = capturedWorkspace()
	const options = {
		mode: 'strict',
		workspaceFiles,
		workspaceSnapshotId: createArtifactSetWorkspaceSnapshotHash(workspaceFiles, undefined, 'tsconfig.json'),
		tsConfigFilePath: 'tsconfig.json',
		securityPolicy: { forbidImports: false },
		format: 'ts-morph'
	} as const

	fact('artifacts in plan', String(plan.artifacts.length))
	fact('workspace files', Object.keys(workspaceFiles).join(', '))

	const result = compileArtifactSet(plan, registry, options)
	assertOk(result, 'compileArtifactSet')

	fact('result', `ok, validation=${String(result.validation)}, complete=${String(result.complete)}`)
	for (const change of result.changes) {
		fact(`change: ${change.path}`, change.kind)
	}

	for (const change of result.changes) {
		if (change.kind === 'createFile') {
			code(change.path, change.sourceText)
			writeOutput(`${id}/${change.path}`, change.sourceText)
		}
	}

	console.log('\n--- an artifact whose output kind cannot satisfy its target is refused')
	const rejected = compileArtifactSet({
		artifacts: [{
			id: 'member-as-file',
			graph: {
				nodes: [{
					id: 'field',
					templateId: 'EffectGenBind',
					typeArguments: { A: { ts: 'unknown' }, E: { ts: 'never' }, R: { ts: 'never' } },
					inputs: { name: literal('value'), source: raw('Effect.void') }
				}],
				finalNodeId: 'field'
			},
			target: { kind: 'createFile', path: 'src/not-a-module.ts' }
		}]
	}, registry, options)
	console.log(`  ok=${rejected.ok} classification=${rejected.ok ? 'n/a' : rejected.classification}`)
	for (const diagnostic of rejected.diagnostics.slice(0, 2)) {
		console.log(`  ${diagnostic.stage}/${diagnostic.code}: ${diagnostic.message}`)
	}

	block('why the workspace snapshot matters', [
		'Every artifact is validated against one captured workspace, pinned by',
		'createArtifactSetWorkspaceSnapshotHash. Change a single byte of any captured',
		'file and the hash no longer matches, so a result cannot be carried across',
		'two different views of the same project.'
	].join('\n'))
}
